<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Identity.Application</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Identity.Domain/Identity.Domain.csproj" />
    <ProjectReference Include="../../../../shared/BuildingBlocks/BuildingBlocks.Application/BuildingBlocks.Application.csproj" />
    <ProjectReference Include="../../../../shared/BuildingBlocks/BuildingBlocks.Contracts/BuildingBlocks.Contracts.csproj" />
  </ItemGroup>
</Project>
